### ISSUE TITLE
Scraping fails with a cryptic error

### ISSUE THREAD

**Issue by mnmkng** [apify/actor-google-search-scraper#12]
Might have to do with being blocked, but it's hard to decipher. We could try to save full HTML of errors which are caused by a successful request, but an unsuccessful data extraction (signifying corrupt HTML) and also not increment the retry count (or use a higher retry count) in case of those errors.

```
ERROR: BasicCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"http://www.google.com/search?hl=en&gl=US&q=chevrolet+express+wagon&uule=w+CAIQICIcMTE3NTMsTmV3IFlvcmssVW5pdGVkIFN0YXRlcw==","retryCount":2,"id":"aqUO7a2kPDddZXb"}
2019-10-08T10:13:49.003Z   SyntaxError: unmatched pseudo-class :first
2019-10-08T10:13:49.004Z     at Object.compile [as pseudo] (/usr/src/app/node_modules/css-select/lib/pseudos.js:388:10)
2019-10-08T10:13:49.006Z     at /usr/src/app/node_modules/css-select/lib/compile.js:99:26
2019-10-08T10:13:49.007Z     at Array.reduce (<anonymous>)
2019-10-08T10:13:49.009Z     at compileRules (/usr/src/app/node_modules/css-select/lib/compile.js:97:15)
2019-10-08T10:13:49.011Z     at /usr/src/app/node_modules/css-select/lib/compile.js:87:32
2019-10-08T10:13:49.012Z     at Array.map (<anonymous>)
2019-10-08T10:13:49.014Z     at compileToken (/usr/src/app/node_modules/css-select/lib/compile.js:87:4)
2019-10-08T10:13:49.015Z     at compileUnsafe (/usr/src/app/node_modules/css-select/lib/compile.js:32:9)
2019-10-08T10:13:49.016Z     at select (/usr/src/app/node_modules/css-select/index.js:18:49)
2019-10-08T10:13:49.018Z     at CSSselect (/usr/src/app/node_modules/css-select/index.js:41:9)
2019-10-08T10:13:49.019Z     at initialize.exports.find (/usr/src/app/node_modules/cheerio/lib/api/traversing.js:40:21)
2019-10-08T10:13:49.021Z     at Node.$.each (/usr/src/app/src/extractors_desktop.js:71:42)
2019-10-08T10:13:49.023Z     at initialize.exports.each (/usr/src/app/node_modules/cheerio/lib/api/traversing.js:300:24)
2019-10-08T10:13:49.024Z     at Object.exports.extractPaidProducts (/usr/src/app/src/extractors_desktop.js:58:49)
2019-10-08T10:13:49.026Z     at CheerioCrawler.handlePageFunction (/usr/src/app/src/main.js:77:42)
2019-10-08T10:13:49.027Z     at CheerioCrawler._handleRequestFunction (/usr/src/app/node_modules/apify/build/cheerio_crawler.js:350:50)
2019-10-08T10:13:49.028Z     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by metalwarrior665** [comment]
What is particularly bad about this? The error message seems pretty straightforward. Should we just wrap it up and/or remove the stack trace?

**Comment by mnmkng** [comment]
It’s a message for the developer, not for the user. They have no idea about any pseudo classes. It should say something like “Received invalid HTML” or “Request was blocked”. I don’t know what it is it’s trying to tell me as a user. Did I do something wrong? Is it broken?

**Comment by metalwarrior665** [comment]
Oh, right. I somehow thought that this error came from user code passed in a custom function (I'm used to that parsing code should never crash:) ). I will look more in-depth where this parsing error can happen.

**Comment by metalwarrior665** [comment]
Haha, so `:first` is not implemented in Cheerio so this path of code actually never worked... Fixed by changing to `.first()`
